#!/bin/bash
# ──────────────────────────────────────────────────────────────────────────────
# IntelliOps Monitor — EC2 Bootstrap Script (Amazon Linux 2023 / Ubuntu 22.04)
#
# Usage (EC2 User Data):  paste this script verbatim in the EC2 Launch Wizard
# Manual run:             sudo bash setup.sh
#
# What this does:
#   1. Installs Docker + Docker Compose
#   2. Installs Ollama and pulls llama3.2 + nomic-embed-text
#   3. Clones / copies the WM-IntelliOps-Monitor stack
#   4. Writes the .env file from instance metadata / environment
#   5. Starts the full docker-compose stack
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

LOG="/var/log/intelliops-monitor-setup.log"
exec > >(tee -a "$LOG") 2>&1

echo "=== IntelliOps Monitor Setup — $(date) ==="

# ── Detect distro ─────────────────────────────────────────────────────────────
if [ -f /etc/os-release ]; then
  . /etc/os-release
  DISTRO="$ID"
else
  DISTRO="unknown"
fi

# ── Package manager ────────────────────────────────────────────────────────────
install_pkg() {
  if command -v dnf &>/dev/null;    then dnf install -y "$@"
  elif command -v apt-get &>/dev/null; then apt-get install -y "$@"
  else echo "Unknown package manager"; exit 1; fi
}

# ── Update system ──────────────────────────────────────────────────────────────
echo "[1/7] Updating system packages…"
if command -v dnf &>/dev/null; then
  dnf update -y
  dnf install -y git curl wget unzip
else
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y git curl wget unzip
fi

# ── Install Docker ─────────────────────────────────────────────────────────────
echo "[2/7] Installing Docker…"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl start docker
systemctl enable docker
usermod -aG docker ec2-user 2>/dev/null || usermod -aG docker ubuntu 2>/dev/null || true

# ── Install Docker Compose v2 ──────────────────────────────────────────────────
echo "[3/7] Installing Docker Compose…"
if ! docker compose version &>/dev/null 2>&1; then
  # Try package manager first (Amazon Linux 2023 / Ubuntu)
  dnf install -y docker-compose-plugin 2>/dev/null || apt-get install -y docker-compose-plugin 2>/dev/null || true
  # Fallback: direct binary (lowercase linux, not uname -s which returns Linux)
  if ! docker compose version &>/dev/null 2>&1; then
    mkdir -p /usr/local/lib/docker/cli-plugins
    curl -fsSL "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-$(uname -m)" \
      -o /usr/local/lib/docker/cli-plugins/docker-compose
    chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  fi
fi
echo "Docker Compose: $(docker compose version)"

# ── Install Ollama ─────────────────────────────────────────────────────────────
echo "[4/7] Installing Ollama…"
if ! command -v ollama &>/dev/null; then
  curl -fsSL https://ollama.ai/install.sh | sh
fi
systemctl start ollama
systemctl enable ollama

# Wait for Ollama to be ready
echo "Waiting for Ollama to start…"
for i in $(seq 1 30); do
  if curl -s http://localhost:11434/api/tags &>/dev/null; then
    echo "Ollama is ready (${i}s)"
    break
  fi
  sleep 2
done

# Pull required models
echo "Pulling llama3.2…"
ollama pull llama3.2 || echo "WARNING: llama3.2 pull failed — will retry on first use"

echo "Pulling nomic-embed-text (for RAG)…"
ollama pull nomic-embed-text || echo "WARNING: nomic-embed-text pull failed"

# ── Deploy monitoring stack ────────────────────────────────────────────────────
echo "[5/7] Deploying IntelliOps Monitor stack…"
DEPLOY_DIR="/opt/intelliops-monitor"
mkdir -p "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

# If deploying from git (uncomment and set your repo URL):
# git clone https://github.com/Workmates-Automations/WM-IntelliOps-Monitor.git .
# For now, assume files are already copied here by the CI/CD or manually.

# ── Write .env ────────────────────────────────────────────────────────────────
echo "[6/7] Writing .env configuration…"

# Fetch instance identity (EC2 metadata)
REGION=$(curl -s --connect-timeout 2 http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null || echo "ap-south-1")
ACCOUNT_ID=$(curl -s --connect-timeout 2 http://169.254.169.254/latest/meta-data/iam/security-credentials/ | head -1 2>/dev/null || echo "")
# Resolve account ID via STS (more reliable)
if command -v aws &>/dev/null; then
  ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "036160411876")
fi

cat > "$DEPLOY_DIR/.env" <<EOF
# Auto-generated by setup.sh on $(date)
AWS_REGION=${REGION}
HOME_ACCOUNT_ID=${ACCOUNT_ID:-036160411876}
CROSS_ACCOUNT_ROLE_NAME=CWMSessionRole

# Ollama
OLLAMA_MODEL=llama3.2

# Monitoring targets — comma-separated Lambda names (leave empty to skip Lambda section)
MONITOR_LAMBDAS=

# DynamoDB tables to monitor
MONITOR_DYNAMO_TABLES=IntelliOps-Tickets,IntelliOps-Alarms,IntelliOps-Sessions

# S3 bucket with AI monitoring events
INTELLIOPS_STRANDS_JOBS_BUCKET=intelliops-websiterca

# Domain
DOMAIN=monitor.wmintelliops.com
CERT_EMAIL=admin@wmintelliops.com
EOF

# ── Start stack ───────────────────────────────────────────────────────────────
echo "[7/7] Starting docker-compose stack…"
chmod +x "$DEPLOY_DIR/nginx/init-cert.sh"
chmod +x "$DEPLOY_DIR/ec2/deploy.sh"
chmod +x "$DEPLOY_DIR/ec2/userdata.sh"
docker compose -f "$DEPLOY_DIR/docker-compose.yml" --env-file "$DEPLOY_DIR/.env" up -d --build

# ── Issue Let's Encrypt certificate ──────────────────────────────────────────
echo "Waiting for nginx to be ready on port 80…"
for i in $(seq 1 24); do
  if curl -sfo /dev/null http://localhost; then
    echo "Nginx ready (${i}s)"
    break
  fi
  sleep 5
done

COMPOSE="docker compose -f $DEPLOY_DIR/docker-compose.yml --env-file $DEPLOY_DIR/.env"

echo "Issuing Let's Encrypt certificate for monitor.wmintelliops.com…"
$COMPOSE stop certbot 2>/dev/null || true
$COMPOSE run --rm --entrypoint certbot certbot \
  certonly --webroot -w /var/www/certbot \
  -d monitor.wmintelliops.com \
  --email admin@wmintelliops.com \
  --agree-tos --no-eff-email \
  --non-interactive 2>&1 \
  && $COMPOSE exec -T nginx nginx -s reload \
  && echo "Certificate issued and nginx reloaded" \
  || echo "WARNING: cert issuance failed — nginx serving self-signed cert until retry"
$COMPOSE start certbot 2>/dev/null || true

# ── Create systemd service for auto-restart on reboot ─────────────────────────
cat > /etc/systemd/system/intelliops-monitor.service <<EOF
[Unit]
Description=IntelliOps Monitor Stack
Requires=docker.service
After=docker.service network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${DEPLOY_DIR}
ExecStart=/usr/bin/docker compose -f ${DEPLOY_DIR}/docker-compose.yml up -d
ExecStop=/usr/bin/docker compose -f ${DEPLOY_DIR}/docker-compose.yml down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable intelliops-monitor.service

# ── Summary ───────────────────────────────────────────────────────────────────
PUBLIC_IP=$(curl -s --connect-timeout 2 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "unknown")
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  IntelliOps Monitor — Setup Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Dashboard:    http://${PUBLIC_IP}"
echo "  API docs:     http://${PUBLIC_IP}/docs"
echo "  Health check: http://${PUBLIC_IP}/health"
echo "  Ollama:       http://localhost:11434 (localhost only)"
echo ""
echo "  Config: ${DEPLOY_DIR}/.env"
echo "  Logs:   docker compose -f ${DEPLOY_DIR}/docker-compose.yml logs -f"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
